In [2]:
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
import warnings
import numpy as np
import os 
os.environ['KMP_DUPLICATE_LIB_OK']='True'
warnings.filterwarnings('ignore')
import pandas_datareader.data as web
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
start_date = "2020-01-01"
end_date = "2020-08-01"
infy_data=yf.download("INFY",start=start_date,end=end_date)
infy_data


[*********************100%%**********************]  1 of 1 completed


Open   High    Low  Close  Adj Close    Volume
Date                                                       
2020-01-02  10.30  10.34  10.23  10.29   9.198479   5688000
2020-01-03  10.29  10.35  10.26  10.31   9.216355   6992200
2020-01-06  10.22  10.25  10.17  10.21   9.126964  10068900
2020-01-07  10.12  10.17  10.10  10.10   9.028632  10589100
2020-01-08  10.00  10.12   9.99  10.09   9.019693  13440400
...           ...    ...    ...    ...        ...       ...
2020-07-27  12.68  12.70  12.55  12.67  11.484728   6335100
2020-07-28  12.75  12.79  12.57  12.58  11.403149   9797300
2020-07-29  12.66  12.92  12.65  12.85  11.647888  13711300
2020-07-30  12.71  12.99  12.69  12.95  11.738533  10135600
2020-07-31  12.97  12.98  12.76  12.85  11.647888   8049700

[147 rows x 6 columns]

In [4]:
infy_data=infy_data.dropna()
infy_data=infy_data.drop(index=infy_data.index[56])
infy_data=infy_data.drop(index=infy_data.index[96])
infy_data

Open   High    Low  Close  Adj Close    Volume
Date                                                       
2020-01-02  10.30  10.34  10.23  10.29   9.198479   5688000
2020-01-03  10.29  10.35  10.26  10.31   9.216355   6992200
2020-01-06  10.22  10.25  10.17  10.21   9.126964  10068900
2020-01-07  10.12  10.17  10.10  10.10   9.028632  10589100
2020-01-08  10.00  10.12   9.99  10.09   9.019693  13440400
...           ...    ...    ...    ...        ...       ...
2020-07-27  12.68  12.70  12.55  12.67  11.484728   6335100
2020-07-28  12.75  12.79  12.57  12.58  11.403149   9797300
2020-07-29  12.66  12.92  12.65  12.85  11.647888  13711300
2020-07-30  12.71  12.99  12.69  12.95  11.738533  10135600
2020-07-31  12.97  12.98  12.76  12.85  11.647888   8049700

[145 rows x 6 columns]

In [5]:
start_date = "2020-08-02"
end_date = "2021-03-02"
yx=yf.download("INFY",start=start_date,end=end_date)
y=yx['Close']
y
#y.columns


[*********************100%%**********************]  1 of 1 completed


Date
2020-08-03    12.920000
2020-08-04    12.640000
2020-08-05    12.650000
2020-08-06    12.830000
2020-08-07    12.600000
                ...    
2021-02-23    17.379999
2021-02-24    17.680000
2021-02-25    17.389999
2021-02-26    17.120001
2021-03-01    17.660000
Name: Close, Length: 145, dtype: float64

In [6]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

xtrain1=scaler.fit_transform(infy_data)
xtrain1

array([[ 0.36601593,  0.30245286,  0.39922346,  0.35208687,  0.31212313,
        -1.18229073],
       [ 0.3585313 ,  0.31006819,  0.42115102,  0.36697136,  0.32671028,
        -0.97760705],
       [ 0.30614032,  0.2339164 ,  0.35536972,  0.29255037,  0.25376754,
        -0.49474378],
       [ 0.23129545,  0.17299526,  0.30420679,  0.21068785,  0.17353006,
        -0.41310258],
       [ 0.14148204,  0.13491936,  0.22380711,  0.20324561,  0.16623609,
         0.03438598],
       [ 0.29865569,  0.43191047,  0.34075134,  0.4934859 ,  0.4507131 ,
         2.38796581],
       [ 0.96477272,  0.9192796 ,  0.68427554,  0.62000116,  0.57471825,
         2.75798783],
       [ 0.85250542,  0.78982199,  0.81583815,  0.79116915,  0.74248718,
         0.06878765],
       [ 0.79262981,  0.72890085,  0.79391128,  0.77628466,  0.7278977 ,
         0.3087048 ],
       [ 0.76269201,  0.75174682,  0.76467453,  0.76884313,  0.72060451,
        -0.20983138],
       [ 0.77017664,  0.75936142,  0.82314734,  0.

In [7]:
y=pd.DataFrame(y)
ytrain1=scaler.fit_transform(y)
ytrain1

array([[-1.25577106],
       [-1.40340175],
       [-1.3981296 ],
       [-1.30322391],
       [-1.42449185],
       [-1.4297645 ],
       [-1.4086744 ],
       [-1.34013145],
       [-1.32958666],
       [-1.36122155],
       [-1.28213381],
       [-1.22413617],
       [-1.31904136],
       [-1.30849656],
       [-1.42449185],
       [-1.32431401],
       [-1.31376871],
       [-1.27686116],
       [-1.32958666],
       [-1.31376871],
       [-1.42449185],
       [-1.3875843 ],
       [-1.3559494 ],
       [-1.49303479],
       [-1.50885274],
       [-1.3875843 ],
       [-1.3454041 ],
       [-1.42449185],
       [-1.34013145],
       [-1.08705028],
       [-1.03432478],
       [-0.91832899],
       [-0.86033135],
       [-0.94996439],
       [-0.89196674],
       [-0.7706983 ],
       [-0.90251154],
       [-1.18722812],
       [-0.91305684],
       [-0.88142144],
       [-0.91832899],
       [-0.78651575],
       [-0.8128785 ],
       [-0.86033135],
       [-0.65997516],
       [-0

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(xtrain1,ytrain1,test_size=0.3)
y_test.shape

(44, 1)

In [9]:
ytrain1

array([[-1.25577106],
       [-1.40340175],
       [-1.3981296 ],
       [-1.30322391],
       [-1.42449185],
       [-1.4297645 ],
       [-1.4086744 ],
       [-1.34013145],
       [-1.32958666],
       [-1.36122155],
       [-1.28213381],
       [-1.22413617],
       [-1.31904136],
       [-1.30849656],
       [-1.42449185],
       [-1.32431401],
       [-1.31376871],
       [-1.27686116],
       [-1.32958666],
       [-1.31376871],
       [-1.42449185],
       [-1.3875843 ],
       [-1.3559494 ],
       [-1.49303479],
       [-1.50885274],
       [-1.3875843 ],
       [-1.3454041 ],
       [-1.42449185],
       [-1.34013145],
       [-1.08705028],
       [-1.03432478],
       [-0.91832899],
       [-0.86033135],
       [-0.94996439],
       [-0.89196674],
       [-0.7706983 ],
       [-0.90251154],
       [-1.18722812],
       [-0.91305684],
       [-0.88142144],
       [-0.91832899],
       [-0.78651575],
       [-0.8128785 ],
       [-0.86033135],
       [-0.65997516],
       [-0

In [10]:
y_train=pd.DataFrame(y_train)
y_train

# Rename the column
y_train1 = y_train.rename(columns={0: 'Close'})

y_train1.columns


Index(['Close'], dtype='object')

In [11]:
#Random Forest

import tensorflow_decision_forests as tfdf
x_train=pd.DataFrame(x_train,columns=infy_data.columns)
x_train['Close2'] = y_train1['Close']
x_train

Open      High       Low     Close  Adj Close    Volume    Close2
0    0.949803  0.896434  0.969328  0.887916   0.837314 -1.224304 -1.034325
1    0.762692  0.812668  0.837765  0.873032   0.822725  0.050347 -1.313769
2   -1.003640 -0.923587 -0.982181 -0.972601  -0.986269 -0.559168 -0.006182
3    2.364366  2.312852  2.248406  2.257257   2.310817 -0.811641  1.243408
4   -1.535036 -1.190117 -1.464577 -1.210748  -1.219688  1.418504  0.020181
..        ...       ...       ...       ...        ...       ...       ...
96   0.141482  0.073998  0.150717  0.076730   0.143629 -0.107960  0.832150
97   0.358531  0.310068  0.421151  0.366971   0.326710 -0.977607 -1.403402
98   0.366016  0.302453  0.399223  0.352087   0.312123 -1.182291 -1.255771
99   0.395954  0.454756  0.326134  0.292550   0.253768 -0.046863 -0.786516
100  0.388469  0.348143  0.391915  0.314876   0.380318  0.620125  1.127413

[101 rows x 7 columns]

In [ ]:
label='Close2'
train_ds=tfdf.keras.pd_dataframe_to_tf_dataset(x_train,label='Close2',task=tfdf.keras.Task.REGRESSION)

In [ ]:
rf=tfdf.keras.RandomForestModel(task=tfdf.keras.Task.REGRESSION)
rf.compile(metrics=["mse"])

In [ ]:
rf.fit(x=train_ds)

In [ ]:
y_test=pd.DataFrame(y_test)
y_test

# Rename the column
y_test1 = y_test.rename(columns={0: 'Close'})

y_test1.columns


In [ ]:
x_test=pd.DataFrame(x_test,columns=infy_data.columns)
x_test['Close2'] = y_test1['Close']
x_test


In [ ]:
test_ds=tfdf.keras.pd_dataframe_to_tf_dataset(x_test,label='Close2',task=tfdf.keras.Task.REGRESSION)

In [ ]:
preds=rf.predict(x=test_ds)

In [ ]:
actual_data=x_test['Close2']
actual_data



In [ ]:
import matplotlib.pyplot as plt
plt.plot(actual_data)
plt.plot(preds)
plt.legend(('Data','Prediction'))